library(MASS)
library(ISLR)
fix(Boston)
names(Boston)
lm.fit-lm(medv~lstat, data=Boston)
attach(Boston)
lm.fit = lm(medv~lstat)
lm.fit
summary(lm.fit)
names(lm.fit)
coef(lm.fit)
confint(lm.fit)
plot(lstat, medv)
abline(lm.fit)
abline(lm.fit, lwd=3)
plot(lstat, medv, col="red")
par(mfrow=c(2,2))
plot(lm.fit)